# Site settings
title: Joe Hamman
header-img: img/home-bg.jpg
email: jhamman@ucar.edu
description: "Joe Hamman"
# baseurl: "/"
url: "http://joehamman.com/"
twitter_username: HammanHydro
github_username:  jhamman
facebook_username:  joehamman

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]


gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"
